# docker-compose up //
version: '3.3'

services:
  solace:
    container_name: solace
    image: solace/solace-pubsub-standard:latest
    hostname: solace
    shm_size: 1g
    ulimits:
      core: 1
      nofile:
        soft: 2448
        hard: 38048
    ports:
      - '55555:55555'
    environment:
      - username_admin_globalaccesslevel=admin
      - username_admin_password=admin
      - system_scaling_maxconnectioncount=100
  interlok: 
    image: adaptrislabs/interlok-solace
    container_name: interlok-solace
    hostname: interlok
    environment:
      - SOLACE_HOST=solace
      - SOLACE_PORT=55555
      - SOLACE_USER=admin
      - SOLACE_PASSWORD=admin
    ports:
      - '8080:8080'
    depends_on:
      - solace
    links:
      - solace:solace
